### PR TITLE
fixing fahrenheit logic

### PR DESCRIPTION
**Pull request by imerin**
This should fix these issues:

Sensibo setting target to 100F on startup

Sensibo always setting temperature unit to celsius

### CODE REVIEW

**Comment by DarylMc** [comment]
@imerin 
Thanks for the work you have put in there.

**Comment by luissimoes** [comment]
sorry for the simple question but how do I use the latest changes? as mentioned in a new issei's Weiluen seems to have disappeared and there isn't a new "package" (main).... but there was this excellent work from @imerin .... so, how can we use this?

**Comment by imerin** [comment]
@luissimoes you can clone my forked repo and then overwrite the homebridge-sensibo-sky directory in your node_modules folder with the contents of the cloned repo.

**Comment by luissimoes** [comment]
> @luissimoes you can clone my forked repo and then overwrite the homebridge-sensibo-sky directory in your node_modules folder with the contents of the cloned repo.

@imerin 
cheers!!!
so basically I should copy the files in **accessories and lib folders** and overwrite the corresponding files in my Raspberry installation of the Homebridge Plugin?

image

**Comment by imerin** [comment]
@luissimoes Yes, I made changes to index.js as well but they are not necessary to get the improved functionality.  

Let me know how it goes for you.

**Pull request merged**
